spring:
  datasource:
  #
  url: jdbc:h2:tcp://localhost/~/study
  username: sa
  password:
  driver-class-name: org.h2.Driver
jpa:
  hibernate:
    ddl-auto: create # drop - create
  properties:
    hibernate:
#      show_sql: true  // System.out 에 하이버네이트 실행 SQL을 남김
      format_sql: true
    logging.level:
      org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL 을 남
    #  org.hibernate.type: trace김